ARG TOPOLVM_VERSION=0.41.1

FROM ghcr.io/topolvm/topolvm:${TOPOLVM_VERSION} AS topolvm

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install --yes --no-install-recommends lvm2 xfsprogs \
    && mkdir -p /etc/topolvm \
    && rm -rf /var/lib/apt/lists/*
COPY --from=topolvm /hypertopolvm /usr/local/bin/hypertopolvm
RUN ln -s /usr/local/bin/hypertopolvm /usr/local/bin/lvmd
